### ISSUE TITLE
Bugs in tutorial code: crash course - methods

### ISSUE THREAD

**Issue by protofarer** [rbwhitaker/rbwhitaker.wikidot.com#5]
[C# methods](http://rbwhitaker.wikidot.com/c-sharp-methods) Section Multiple Parameters' code block has 2 mistakes:

1. declares a void method but returns an integer
2. loop does opposite of what it's supposed to, that is, it continues while input is within the range instead of while outside

Current code block, verbatim:
```
static void GetNumberBetween(string prompt, int min, int max)
{
    int parsedNumber;
    do
    {
        Console.Write(prompt);
        string input = Console.ReadLine();
        parsedNumber = Convert.ToInt32(input);       
    }
    while (parsedNumber >= min && parsedNumber <= max);
 
    return parsedNumber;
}
```

Thanks.

**Comment by rbwhitaker** [comment]
Great catch! Thanks for reporting it. I got both of those fixed.
